openapi: 3.0.0
info:
  title: movies
  contact: {}
  version: '1.0'
servers:
- url: http://localhost:8080/api
  variables: {}
paths:
  /tmdb/movies:
    get:
      tags:
      - movie
      summary: getMovies
      operationId: getMovies
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
